config/routes.rb
Rails.application.routes.draw do
  
  # Devise routes for admin and users
  
  devise_for :admin, controllers: { sessions: 'admin/sessions', registrations: 'admin/registrations' }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # Root route
  root 'pages#home'

  # Admin namespace for products
  namespace :admin do
    resources :products
    resources :user_checkouts, only: [:index, :show]
  end


  # Users namespace for products, cart, and checkout
  namespace :users do
    resources :products, only: [:index, :show]
    
    # Cart routes
    resource :cart, only: [:show, :update, :destroy] do
      post 'add_item/:product_id', to: 'carts#add_item', as: 'add_item'
      delete 'remove_item/:id', to: 'carts#remove_item', as: 'remove_item_from_cart' # Renamed to ensure uniqueness
      post 'checkout', to: 'carts#checkout', as: 'checkout'
    end
    
    # Checkout route
    resource :checkout, only: [:show]
  end
  
  # Standalone route for removing item from cart
  delete '/users/cart/remove_item/:id', to: 'users/carts#remove_item', as: 'remove_item_from_cart' # Renamed to ensure uniqueness

end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_product, only: [:show, :edit, :update, :destroy]
  
    def index
      @products = params[:search].present? ? Product.where("name ilike '%#{params[:search]}%'") : Product.all
      @user_checkouts = Checkout.all
    end

    def show
      render
    end
  
    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
  
      if @product.save
        redirect_to admin_products_path, notice: 'Product was successfully created.'
      else
        render :new
      end
    end

    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      @product = Product.find(params[:id])
  
      if @product.update(product_params)
        redirect_to admin_products_path, notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to admin_products_path, notice: 'Product was successfully deleted.'
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to admin_products_path
    rescue ActiveRecord::InvalidForeignKey
      redirect_to admin_products_path,
        alert: "Unable to delete product <strong>#{@product.name}</strong> due to item is in users cart"
    end
  
    private
  
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  def index
    @products = Product.all
    @checkout_history = current_user.checkouts.includes(:checkout_items)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.slim
= form_with(model: @product, url: admin_products_path, method: :post) do |form|
  div
    = form.label :name
    br
    = form.text_field :name

  div
    = form.label :description
    br
    = form.text_area :description

  div
    = form.label :price
    br
    = form.text_field :price
    br
    br
  div
    = form.submit 'Create Product'
    

app/views/admin/products/_product.html.slim
div id="#{dom_id product}"
  p
    strong Name:
    =< product.name
  p
    strong Description:
    =< product.description
  p
    strong Price:
    =< product.price

app/views/admin/products/edit.html.slim
h3 Edit Product

= form_with(model: @product, url: admin_product_path(@product), method: :patch) do |form|
  div
    = form.label :name
    br
    = form.text_field :name

  div
    = form.label :description
    br
    = form.text_area :description

  div
    = form.label :price
    br
    = form.text_field :price
    br
    br
  div
    = form.submit 'Update Product'
    br
    = link_to 'Back', admin_products_path

app/views/admin/products/index.html.slim
h1 Admin Products

= link_to "Sign out", destroy_admin_session_path, method: :delete, data: { turbo_method: :delete }
br
= link_to "Update Information", edit_admin_registration_path
br
br
br
= link_to 'New Product', new_admin_product_path
br
br
br

/ form action="#{admin_products_path}"
/   label for="Search" placeholder="Search"
/   input name="search" id="search" type='text'
/   button type="submit" Submit 

= form_tag action="#{admin_products_path}", method: :get, data: { turbo_frame: "product_item", turbo_action: "advance", controller: "search", action: "input->search#submit" } do |f| 
  = text_field_tag "search", nil, placeholder: "Search...", value: params[:search]
  = submit_tag "Search"
br
turbo-frame#product_list
  table
    thead
      tr
        th Name
        th Description
        th Price
        th Actions

    tbody
      - @products.each do |product|
        tr
          td= product.name
          td= product.description
          td= product.price
          td
            = link_to 'Show', admin_product_path(product)
            = link_to 'Edit', edit_admin_product_path(product)
            = link_to 'Delete', admin_product_path(product), data: { turbo_method: 'delete', confirm: 'Are you sure?' }




h2 User Checkout History
table
  thead
    tr
      th User Email
      th Date & Time
      th Total Price
      th Other Details

  tbody
    - @user_checkouts.each do |checkout|
      tr
        td= checkout.user.email
        td= checkout.created_at.strftime("%Y-%m-%d %H:%M:%S")
        td= number_to_currency(checkout.total_price)
        td= link_to 'View checkout details', admin_user_checkout_path(checkout)

app/views/admin/products/new.html.slim
h1 New Product

= render 'form'

= link_to 'Back', admin_products_path

app/views/admin/products/show.html.slim
h1 Product Details
p Name: #{@product.name}
p Description: #{@product.description}
p Price: #{@product.price}

= link_to 'Back', admin_products_path
= link_to 'Delete', admin_product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }